### ISSUE TITLE
ERROR: Soil thermal nodes do not extend below bottom soil layer

### ISSUE THREAD

**Issue by lizaclark** [UW-Hydro/VIC#377] opened 2016-01-27 19:45 UTC
I ran VIC v. 4.2.c over a basin in the Columbia River Basin (PNW, U.S.) in energy balance mode (3-hour time step). The model ran to completion for all cells; however, at least one cell gave the following error:

"ERROR: Soil thermal nodes do not extend below bottom soil layer, currently unable to handle this condition."

I have 10 soil thermal nodes and 3 soil layers. FROZEN_SOIL is FALSE. Damping depth = 4 and total soil depth = 4.0378. This error message is confusing and probably unnecessary when FROZEN_SOIL=FALSE.

**Comment by jhamman** [comment] 2016-02-02 06:07
@tbohn - any idea what is going on here?

**Comment by tbohn** [comment] 2016-02-02 06:13
The problem is fairly trivial - the check just needs to be modified to only happen when FROZEN_SOIL = TRUE.

**Comment by jhamman** [comment] 2016-02-03 06:08
Okay, so let's make sure the following are true in VIC 5:
 - this check is only performed when it matters (FROZEN_SOIL is TRUE)
 - If we say ERROR, we actually raise an error.

**Comment by bartnijssen** [comment] 2016-02-03 06:25
Agreed

**Comment by lizaclark** [comment] 2016-02-03 19:02
This sounds good to me. The only other thing that might be useful is if the error message said: </br> "ERROR: Soil thermal nodes do not extend below bottom soil layer, currently unable to handle this condition. Check that soil thermal damping depth is greater than total soil column depth."

**Comment by tbohn** [comment] 2016-02-15 20:26
Actually, the solution is not as trivial as I'd thought, although it's still fairly simple to solve.  My previous response was too hasty - I relied on my imperfect memory of the code without confirming by checking the code.

It turns out that even when FROZEN_SOIL is FALSE, the code estimates soil layer temperatures (using QUICK_FLUX scheme if appropriate).  Obviously these temperatures won't be very accurate if the soil goes below freezing, but it at least guarantees that you can get model estimates of temperature under all modes of simulation.  So, I can't just ignore the check when FROZEN_SOIL is FALSE.  Fortunately when FROZEN_SOIL is FALSE, no other variables depend on these layer temperature estimates (I originally implemented them so that John Yearsley could have temperature estimates for his stream temperature model), i.e. they have no effect on the water and energy balances.  Therefore, I propose that in this case we just extend the temperature of the deepest node down to the bottom of the bottom soil layer.

**Comment by tbohn** [comment] 2016-02-18 05:44
@lizaclark can you point me to the input parameters, forcings, etc for a grid cell that failed?  I'm trying to reproduce the error but not able to - could be my settings or something...

**Comment by lizaclark** [comment] 2016-02-18 06:27
@tbohn : Check your email for the test files.

**Comment by bartnijssen** [comment] 2016-03-17 04:58
@tbohn : Just checking that this is still in the works ...

**Comment by tbohn** [comment] 2016-04-10 03:59
PR is on the way...

**Comment by tbohn** [comment] 2016-04-10 05:06
OK, I can't reproduce this in 5.0 when FROZEN_SOIL is FALSE.  In 5.0, the only way to get to that error message is when FROZEN_SOIL is TRUE.  I've fixed the bug for this case: instead of giving an error when the soil thermal nodes don't extend to the bottom of the soil column, the soil layer temperatures are computed assuming that the temperature of the deepest node pertains to all depths below it.  Since nothing else in the model depends on these reported soil layer (not node) temperatures, it seems harmless enough to allow a soil layer temperature to be computed for this case.

I can examine 4.2.c and try to find a fix for that release to go into 4.2.d, if people feel this is important.

**Comment by jhamman** [comment] 2016-04-11 21:27
closed via #467

**Closed by jhamman** 2016-04-11 21:27 UTC
Labels: bug, documentation, question
