### ISSUE TITLE
Vapor pressure disaggregation has strange dips during early morning

### ISSUE THREAD

**Issue by arbennett** [UW-Hydro/VIC#667] opened 2017-01-18 00:10 UTC
While working on MetSim I can across a strange phenomena that VIC 4.2 produces when running with the FORCE_OUTPUT option.  Using the Stehekin test data the behavior can be seen in the plot below.  This is taken from a slice [96:128] of the output data.  

![vp_issue](https://cloud.githubusercontent.com/assets/7518706/22045459/329dfec4-dccf-11e6-910e-1e71c1f13424.png)

**Comment by tbohn** [comment] 2017-01-18 00:13
I believe this is coming from the constraint that VP cannot exceed saturation vapor pressure.  This isn't a bug.

The algorithm for disaggregating VP is as follows:
1. Assume "daily" value of VP corresponds to sunrise
2. Linearly interpolate between sunrises of each day to get hourly values
3. In those hours when saturation pressure is less than VP, set VP = saturation pressure

**Comment by bartnijssen** [comment] 2017-01-18 01:35
Well - if it's not a bug then it is not right either. It makes the time series look very strange and even if the code correctly implements what you describe above then the resulting time series looks just plain strange and not physical at all. This is exactly why I want to take the out of VIC and make this explicit, because this odd behavior is completely invisible to anyone.

**Comment by bartnijssen** [comment] 2017-01-18 01:36
@arbennett : Can you replace the figure with one that has a line instead of dots and a few more days. That makes it immediately obvious that the dips are an artifact of the algorithm not a reflection of some physical process.

**Comment by arbennett** [comment] 2017-01-18 01:56
@bartnijssen here's an updated plot:

![vp_problem](https://cloud.githubusercontent.com/assets/7518706/22047770/bf31616a-dcdd-11e6-8130-4e313d43b017.png)

@tbohn This is the code I have been looking at for the vapor pressure disaggregation: https://github.com/UW-Hydro/VIC/blob/7c3556ba31b8df8ad292ace10e0a2845dd81276b/src/initialize_atmos.c#L1220-L1263

**Comment by arbennett** [comment] 2017-01-18 02:01
@bartnijssen humidity isn't written out in the setup I have.  Do you know if I can set something in the `global_param` file to make it output?

**Comment by tbohn** [comment] 2017-01-18 02:33
@arbennett and @bartnijssen Just so you understand why I did what I did, let me give a little background.  Note - I'm not arguing with you on this.  I just want to make sure people understand what I did, so they don't think "This guy Ted just seemed to mess up everything he put his hands on."

1. Before I added the linear interpolation, the "disaggregation" was to hold VP constant during the day, resulting in a step function.  I agree, those little dips look unphysical, but I ask you to consider how physical the step function looks.
2. Yes, @bartnijssen is correct, relative humidity (RH) is very useful to look at in this context, as is vapor pressure deficit (VPD).  In fact, both of those variables start looking strange when you have a step function for VP.  When we wrote the Bohn et al 2013 MTCLIM evaluation paper, I did compare (don't recall if the plots are in the paper itself) hourly RH with observations and found a much better fit than using the step function.  And given that several functions in VIC are dependent on VPD, you might want to check how those look with and without the linear interpolation before making your final decision.
3. When I implemented the linear interpolation, of course I made sure there was an option to not use it (and go back to the previous step behavior) if one didn't like it.

@bartnijssen yes, I understand why you wanted to take the forcing processing out of VIC.  It makes sense.

@arbennett yes, you can output RH by specifying OUT_REL_HUMID in out global param file.

**Comment by tbohn** [comment] 2017-01-18 02:46
Of course, people still might conclude that "This guy Ted seemed to mess up MOST of what he put his hands on", but hopefully the VP disaggregation won't be on the list...

**Comment by bartnijssen** [comment] 2017-01-18 18:06
@tbohn : No need to fall on your own sword. At some point you have to make a decision on how to handle things like RH > 100% and it all seems like a reasonable procedure, but you have to admit the curve looks odd. My guess is that those periods correspond to brief periods when Rhum reaches 100%. The nice part of creating the met series independently is that it showcases the consequences of the assumptions we make more explicitly.  

@arbennett : Can you overlay the temperature and RHUM on the same plot (or make two more plots with the same x-axis?

At this time the decision we need to make is whether we want to emulate this behavior exactly (at least in MetSim 1.0) or whether we want to change it. My inclination would be: Since this is NOT a bug but intentional, we reproduce the behavior in MetSim 1.0 and then evaluate later whether we want to change this. @tbohn : let me know what you think.

@arbennett : I think your procedure in MetSim already does almost all of this. I think the only constraint you need to add (after the interpolation) is that : `vp = vp_sat if vp > vp_sat`. You can calculate `vp_sat` as a function of the air temperature.

**Comment by tbohn** [comment] 2017-01-18 18:16
@bartnijssen Your plan seems reasonable to me - v1.0 just translates the same functionality to the stand-alone tool.  Subsequent versions can improve it.

**Comment by bartnijssen** [comment] 2017-01-18 18:22
After @arbennett adds the additional plots I will close the issue and I will open another one to examine this issue more closely in the future.

**Comment by arbennett** [comment] 2017-01-18 19:04
Here are the updated plots:

![vp_rh](https://cloud.githubusercontent.com/assets/7518706/22078631/87c44284-dd6d-11e6-820a-35d2db5d4de3.png)
![temp](https://cloud.githubusercontent.com/assets/7518706/22078681/b24ce8da-dd6d-11e6-8eae-d9cd7929923b.png)

Thanks @tbohn and @bartnijssen for the discussion, I'll make sure this behavior gets implemented in MetSim.

**Comment by bartnijssen** [comment] 2017-01-18 21:14
OK, thanks for the updated plots. They do clearly indicate what is going on. Closing it here - we can continue this in MetSim (https://github.com/UW-Hydro/MetSim/issues/15).

**Closed by bartnijssen** 2017-01-18 21:14 UTC
Labels: science
