### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#463] opened 2016-04-08 21:45 UTC
Using valgrind to run the latest develop branch image driver on Stehekin test case, found unfreed memory in the following places:

Image Driver:
vic_init.c: 74
alloc_atmos.c: 41, 45
vic_mpi_support.c: 61, 62, 63
get_nc_field.c: 44, 124
get_nc_dimension.c: 42
make_veg_var.c: 46
make_snow_data.c: 50
make_cell_data.c: 44
make_energy_bal.c: 49
vic_finalize.c: 106  (from @jhamman's comment below)

Classic Driver:
set_output_defaults.c: 94

Note: some of the line numbers may change as commits continue to be merged into the code.

**Comment by jhamman** [comment] 2016-04-11 17:21
I'll also add: https://github.com/UW-Hydro/VIC/pull/460/files#r58979183
vic_finalize.c: 106

**Comment by tbohn** [comment] 2016-04-29 17:41
I'll work on this today & over the weekend.

**Comment by tbohn** [comment] 2016-05-02 23:51
I've been able to solve the following leaks:
vic_init.c
alloc_atmos.c
make_veg_var.c
make_cell_data.c
make_snow_data.c
make_energy_bal.c
set_output_defaults.c

The remaining leaks are related to creation of MPI data structs (mpi_nc_file_struct_type, mpi_option_struct_type, and mpi_param_struct_type) and the opening of nc files in get_nc_dimension.c and get_nc_field.c.

For the MPI data structs, there is a call to MPI_Finalize(), which one would think would free all MPI-related data structures, in vic_image.c.  So, not sure what to do there.  @jhamman suggested possibly the function MPI_Type_free().

For the nc_file opening in get_nc* functions, I'm not sure why these are happening, since nc_close() is called at the end of each function.

**Comment by tbohn** [comment] 2016-05-03 18:42
@jhamman There still are 3 outstanding leaks in get_nc_dimensions.c and get_nc_field.c that I wasn't able to fix in my PR (#490).  So it might be premature to close this issue...  Or we should open a new issue for just those leaks...

**Comment by bartnijssen** [comment] 2016-05-24 23:09
Do we still have memory leaks? Would be good to list the remaining ones in some detail. Ideally it would state which version of the driver, the platform (OS and version), nc library (version) and compiler (name and version).

**Comment by tbohn** [comment] 2016-05-26 19:38
Yes, we still have the following memory leaks for image driver, os = gnu/linux x86_64, compiler = gcc 4.4.7, netcdf 4 (I think; it's whatever is on the UW lab machines):
get_nc_field.c: 44, 124
get_nc_dimension.c: 42
I created a new issue for these remaining leaks (#513) but perhaps that was unnecessary.  I can close  that new issue if you'd like to continue using this one.

**Comment by bartnijssen** [comment] 2016-05-28 00:23
@tbohn: I have copied the text from #513 here, so we can continue the discussion in one place:

From @tbohn (text from #513):
_Most of the memory leaks from that issue have been resolved, and it was getting difficult to see which issues remained. The remaining ones are:

Image Driver:
get_nc_field.c: 44, 124
get_nc_dimension.c: 42

These are puzzling, as the functions they appear in do an nc_open, then query the nc filehandle for specific information, and then do an nc_close. On the surface it looks like all memory allocation and freeing is handled by the netcdf library functions and that all memory allocated would be freed again by the nc_close() call. But perhaps further investigation will reveal the cause._

**Comment by bartnijssen** [comment] 2016-05-28 00:34
I think we can safely disregard the memory errors on `nc_open` for now, because in all cases the `nc_open` statement is matched by an `nc_close` before the end of the function. Doing a search for [nc_open valgrind memory leak](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=nc_open+valgrind+memory+leak) shows that others have seen similar occurrences depending on the `netCDF` and `HDF` libraries. 

I am a little surprised that it does not show up for every occurrence on `nc_open` though. I understand `get_nc_float`, because I am not sure that is ever used, but what about the `nc_open` in `get_nc_varndimensions`?

**Comment by bartnijssen** [comment] 2016-08-17 21:55
@jhamman : If the remaining memory errors are associated with `nc_open()` and `nc_close()` then I would close this issue out, since we have no control over what the netcdf library does behind the scenes.

**Comment by jhamman** [comment] 2016-08-17 22:07
yes, we can close this.  I'm not seeing any of these except on OSX but I'm fine attributing that to a issue with Valgrind.

**Closed by jhamman** 2016-08-17 22:07 UTC
Labels: all drivers, bug
